In [ ]:
#Step 1
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [ ]:
#step2 Read data into dataframe
names = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model_year','origin','car_name']
df = pd.read_csv('/content/auto-mpg.data',names=names,sep='\s+')

<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-846799929.py:3: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('/content/auto-mpg.data',names=names,sep='\s+')

In [ ]:
df.head()

    mpg  cylinders  displacement  ... model_year  origin                   car_name
0  18.0          8         307.0  ...         70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...         70       1          buick skylark 320
2  18.0          8         318.0  ...         70       1         plymouth satellite
3  16.0          8         304.0  ...         70       1              amc rebel sst
4  17.0          8         302.0  ...         70       1                ford torino

[5 rows x 9 columns]

In [ ]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
df['horsepower'] = df['horsepower'].astype('float')

ValueError: could not convert string to float: '?'

In [ ]:
df = df[df['horsepower'] != '?']

In [ ]:
df['horsepower'] = df['horsepower'].astype('float')

In [ ]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
df.head()

    mpg  cylinders  displacement  ...  model_year  origin                   car_name
0  18.0          8         307.0  ...          70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...          70       1          buick skylark 320
2  18.0          8         318.0  ...          70       1         plymouth satellite
3  16.0          8         304.0  ...          70       1              amc rebel sst
4  17.0          8         302.0  ...          70       1                ford torino

[5 rows x 9 columns]

In [ ]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64

In [ ]:
#step 3
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'car_name'],
      dtype='object')

In [ ]:
X = df[['cylinders', 'displacement', 'horsepower', 'weight','acceleration', 'model_year']]
y = df['mpg']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=32)

In [ ]:
X_train

     cylinders  displacement  horsepower  weight  acceleration  model_year
260          6         225.0       110.0  3620.0          18.7          78
184          4         140.0        92.0  2572.0          14.9          76
174          6         171.0        97.0  2984.0          14.5          75
64           8         318.0       150.0  4135.0          13.5          72
344          4          86.0        64.0  1875.0          16.4          81
..         ...           ...         ...     ...           ...         ...
72           8         304.0       150.0  3892.0          12.5          72
107          6         232.0       100.0  2789.0          15.0          73
272          4         151.0        85.0  2855.0          17.6          78
352          4          98.0        65.0  2380.0          20.7          81
103          8         400.0       150.0  4997.0          14.0          73

[313 rows x 6 columns]

In [ ]:
#step6
lr = LinearRegression()

In [ ]:
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
lr.score(X_test,y_test)

0.7942349075428586