In [2]:
#Step 1
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [3]:
#Step2 read data into data frame
names = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration ', 'model_year', 'origin', 'car_name']
df = pd.read_csv('auto-mpg.data', names=names, na_values='?', sep='\s+')

<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-1655590682.py:3: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('auto-mpg.data', names=names, na_values='?', sep='\s+')

In [4]:
df.dtypes

mpg              float64
cylinders          int64
displacement     float64
horsepower       float64
weight           float64
acceleration     float64
model_year         int64
origin             int64
car_name          object
dtype: object

In [5]:
df = df[df['horsepower'] != '?'] # Clearing null values

In [6]:
df['horsepower'] = df['horsepower'].astype(float)

In [15]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.0,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.0,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.0,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.0,2720.0,19.4,82,1,chevy s-10

In [7]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [8]:
df.dtypes

mpg              float64
cylinders          int64
displacement     float64
horsepower       float64
weight           float64
acceleration     float64
model_year         int64
origin             int64
car_name          object
dtype: object

In [9]:
df.isna().sum()

mpg              0
cylinders        0
displacement     0
horsepower       6
weight           0
acceleration     0
model_year       0
origin           0
car_name         0
dtype: int64

In [10]:
# Step 3
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration ', 'model_year', 'origin', 'car_name'],
      dtype='object')

In [11]:
# mpg is the target column
X = df[['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration ', 'model_year']] # Matrix multiple coloumns
Y = df['mpg'] # Vector

In [12]:
# Split data between test and train

X_train, X_test, y_train, y_test  = train_test_split(X,Y, test_size= 0.2, random_state= 42)

In [13]:
X_train

     cylinders  displacement  horsepower  weight  acceleration   model_year
3            8         304.0       150.0  3433.0           12.0          70
18           4          97.0        88.0  2130.0           14.5          70
376          4          91.0        68.0  2025.0           18.2          82
248          4          91.0        60.0  1800.0           16.4          78
177          4         115.0        95.0  2694.0           15.0          75
..         ...           ...         ...     ...            ...         ...
71           3          70.0        97.0  2330.0           13.5          72
106          8         350.0       180.0  4499.0           12.5          73
270          4         134.0        95.0  2515.0           14.8          78
348          4          89.0        62.0  2050.0           17.3          81
102          4          97.0        46.0  1950.0           21.0          73

[318 rows x 6 columns]

In [16]:
# Step 6
lr = LinearRegression()

In [20]:
# Fit data to object
# Fill missing values with the mean of each column
X_train = X_train.fillna(X_train.mean())
X_test = X_test.fillna(X_test.mean())

lr.fit(X_train, y_train)

LinearRegression()

In [21]:
lr.score(X_test, y_test)

0.8243955390048996

We should take 80 to 85 % accuracy however with medical data it should be 90% data. The above one is just over 80% so we can choose a different model