In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense

In [ ]:
texts=[
    "win lottery now",
    "claim your free money",
    "lottery winner announced",
    "meeting at office tomorrow",
    "project discussion with team",
    "family dinner at home"
]


labels=["spam","spam","spam","ham","ham","ham"]

In [ ]:
df = pd.DataFrame({"text":texts,"label":labels})
df.head()

                           text label
0               win lottery now  spam
1         claim your free money  spam
2      lottery winner announced  spam
3    meeting at office tomorrow   ham
4  project discussion with team   ham

In [ ]:
label_encoder = LabelEncoder()
df['label'] = label_encoder.fit_transform(df['label'])
df.head()

                           text  label
0               win lottery now      1
1         claim your free money      1
2      lottery winner announced      1
3    meeting at office tomorrow      0
4  project discussion with team      0

In [ ]:
y = df['label'].values
y

array([1, 1, 1, 0, 0, 0])

In [ ]:
tokenizer=Tokenizer(num_words=1000,oov_token="<OOV>")
tokenizer.fit_on_texts(df['text'])

In [ ]:
tokenizer

In [ ]:
X_seq = tokenizer.texts_to_sequences(df['text'])
print("Sequences ",X_seq)

Sequences  [[4, 2, 5], [6, 7, 8, 9], [2, 10, 11], [12, 3, 13, 14], [15, 16, 17, 18], [19, 20, 3, 21]]